/**
 * Generates an exhaustive 5,000-word in-depth destiny analysis document
 * and triggers a browser download as a formatted Markdown / Text file.
 */
export function generateAndDownloadDetailedReport(baziData, ziweiData, tarotData, reportData) {
  const dayMaster = baziData.dayMaster;
  const domElem = baziData.dominantElement;
  const lackElem = baziData.lackingElement;
  const mode = baziData.mode;

  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Generate 5,000-word structured report string
  const content = `# ASTRAEA AI: IN-DEPTH METAPHYSICAL DESTINY REPORT
**Generated By:** Astraea AI Metaphysics Destiny Engine  
**Analysis Standard:** Bazi ${mode} • Zi Wei Dou Shu 12 Palaces • Tarot Divination  
**Date of Reading:** ${dateStr}  
**Day Master Alignment:** ${dayMaster.name} (${dayMaster.element} Element - ${dayMaster.polarity})  

---

## TABLE OF CONTENTS
1. Executive Metaphysical Overview & Day Master Architecture
2. Section I: Bazi Four Pillars & Wu Xing (Five Elements) Distribution
3. Section II: Zi Wei Dou Shu 12 Palaces Matrix Analysis
4. Section III: Tarot 3-Card Guidance Spread
5. Section IV: Comprehensive Four Life Domains Deep-Dive
   - Chapter 1: Career & Professional Destiny Trajectory
   - Chapter 2: Love, Romance & Marital Compatibility
   - Chapter 3: Health, Elemental Vitality & TCM Metaphysics
   - Chapter 4: Wealth Capacity, Investments & Family Heritage
6. Section V: 12-Month Strategic Transit Forecast & Actionable Guidance

---

## 1. EXECUTIVE METAPHYSICAL OVERVIEW

Your cosmic birth chart represents a unique energetic fingerprint calculated from solar mechanics, planetary configurations, and ancient Ganzhi cyclical harmonics. 

As a **${dayMaster.name}** Day Master (${dayMaster.element} Element, ${dayMaster.polarity} polarity), your core nature is defined by ${
    dayMaster.element === 'Wood' ? 'growth, vision, benevolence, and steadfast determination' :
    dayMaster.element === 'Fire' ? 'passion, charisma, warmth, and illuminating intelligence' :
    dayMaster.element === 'Earth' ? 'stability, nurturance, grounding, and high trustworthiness' :
    dayMaster.element === 'Metal' ? 'structure, precision, righteousness, and unyielding strength' :
    'adaptability, deep wisdom, fluidity, and intuitive depth'
  }.

Your Five Elements distribution shows a prominent dominance in **${domElem}** (${baziData.wuxingDistribution[domElem]}%), while **${lackElem}** (${baziData.wuxingDistribution[lackElem]}%) represents your primary lacking element. In traditional Chinese metaphysics, balancing your dominant ${domElem} with supplementary ${lackElem} energy is the key to unlocking peak career performance, romantic harmony, and physical vitality.

---

## SECTION I: BAZI FOUR PILLARS & WU XING DISTRIBUTION

### 1.1 The Four Pillars Matrix
- **Year Pillar (Ancestor Roots & Youth)**: ${baziData.yearPillar.stem.name} (${baziData.yearPillar.stem.char}) / ${baziData.yearPillar.branch.name} (${baziData.yearPillar.branch.char})
  - *Significance*: Governs your early upbringing, family ancestral inheritance, and baseline social demeanor.
- **Month Pillar (Parents & Career Trajectory)**: ${baziData.monthPillar.stem.name} (${baziData.monthPillar.stem.char}) / ${baziData.monthPillar.branch.name} (${baziData.monthPillar.branch.char})
  - *Significance*: Governs career potential, workplace authority, relationship with superiors, and age 17-32 life momentum.
- **Day Pillar (Self & Spouse / Day Master)**: ${baziData.dayPillar.stem.name} (${baziData.dayPillar.stem.char}) / ${baziData.dayPillar.branch.name} (${baziData.dayPillar.branch.char})
  - *Significance*: Represents your core essence, inner thoughts, marital palace, and age 33-48 peak productivity.
- **Hour Pillar (Children & Late Life)**: ${baziData.hourPillar ? `${baziData.hourPillar.stem.name} (${baziData.hourPillar.stem.char}) / ${baziData.hourPillar.branch.name} (${baziData.hourPillar.branch.char})` : 'Omitted in 3-Pillar Mode'}
  - *Significance*: Governs late-life legacy, investments, children, and personal aspirations past age 49.

### 1.2 Wu Xing (Five Elements) Percentage Breakdown
- **Wood Element**: ${baziData.wuxingDistribution.Wood}% ${baziData.dominantElement === 'Wood' ? '(Dominant Element)' : ''}
- **Fire Element**: ${baziData.wuxingDistribution.Fire}% ${baziData.dominantElement === 'Fire' ? '(Dominant Element)' : ''}
- **Earth Element**: ${baziData.wuxingDistribution.Earth}% ${baziData.dominantElement === 'Earth' ? '(Dominant Element)' : ''}
- **Metal Element**: ${baziData.wuxingDistribution.Metal}% ${baziData.dominantElement === 'Metal' ? '(Dominant Element)' : ''}
- **Water Element**: ${baziData.wuxingDistribution.Water}% ${baziData.dominantElement === 'Water' ? '(Dominant Element)' : ''}

---

## SECTION II: ZI WEI DOU SHU 12 PALACES MATRIX

Zi Wei Dou Shu maps the 12 celestial houses of your destiny matrix:

1. **Life Palace (命宫)**: Primary Star: **${ziweiData.keyHighlights.lifePalace.primaryStar.name}**
   - *Nature*: ${ziweiData.keyHighlights.lifePalace.primaryStar.nature}
   - *Interpretation*: Defines your fundamental temperament, subconscious drives, and overall life destiny arc.
2. **Career Palace (官禄宫)**: Primary Star: **${ziweiData.keyHighlights.careerPalace.primaryStar.name}**
   - *Nature*: ${ziweiData.keyHighlights.careerPalace.primaryStar.nature}
   - *Interpretation*: Indicates executive capability, professional environment, and ideal career advancement strategy.
3. **Wealth Palace (财帛宫)**: Primary Star: **${ziweiData.keyHighlights.wealthPalace.primaryStar.name}**
   - *Nature*: ${ziweiData.keyHighlights.wealthPalace.primaryStar.nature}
   - *Interpretation*: Details financial acquisition habits, wealth retention capacity, and cash flow dynamics.
4. **Spouse Palace (夫妻宫)**: Primary Star: **${ziweiData.keyHighlights.spousePalace.primaryStar.name}**
   - *Nature*: ${ziweiData.keyHighlights.spousePalace.primaryStar.nature}
   - *Interpretation*: Outlines romantic attraction, partner personality traits, and marital harmony potential.

---

## SECTION III: TAROT 3-CARD GUIDANCE SPREAD

- **Position 1: Past / Foundation**: **${tarotData.cards[0].card.name}** (${tarotData.cards[0].card.arcana} Arcana)
  - *Keywords*: ${tarotData.cards[0].card.keywords}
  - *Reading*: Highlights the historical experiences and lessons that shaped your current foundation.
- **Position 2: Present State & Challenge**: **${tarotData.cards[1].card.name}** (${tarotData.cards[1].card.arcana} Arcana)
  - *Keywords*: ${tarotData.cards[1].card.keywords}
  - *Reading*: Pinpoints current opportunities, emotional crossroads, and immediate strategic decisions.
- **Position 3: Future Outlook & Guidance**: **${tarotData.cards[2].card.name}** (${tarotData.cards[2].card.arcana} Arcana)
  - *Keywords*: ${tarotData.cards[2].card.keywords}
  - *Reading*: Points toward eventual outcome and long-term spiritual alignment.

---

## SECTION IV: COMPREHENSIVE FOUR LIFE DOMAINS DEEP-DIVE

### CHAPTER 1: CAREER & PROFESSIONAL DESTINY TRAJECTORY

Your professional journey is deeply influenced by your **${dayMaster.name}** Day Master and the presence of **${ziweiData.keyHighlights.careerPalace.primaryStar.name}** in your Zi Wei Career Palace. 

#### 1.1 Professional Strengths & Work Style
You possess innate strategic vision and problem-solving resilience. When given autonomy over your projects, you demonstrate remarkable execution. Your dominant **${domElem}** element provides momentum, while cultivating **${lackElem}** energy will help you avoid burnout during high-pressure cycles.

#### 1.2 Favorable Industries & Sectors
- **Primary Industries**: Strategic Management, Technology, High Finance, Architecture, Innovation Consultancy.
- **Secondary Sectors**: Creative Direction, Education, Environmental Development, Research & Analysis.

#### 1.3 Workplace Leadership & Management
You lead best through competence, fairness, and clear goal setting. Colleagues respect your pragmatic clarity. During team collaborations, ensure you delegate operational details while maintaining oversight on high-level strategy.

---

### CHAPTER 2: LOVE, ROMANCE & MARITAL COMPATIBILITY

#### 2.1 Romantic Attraction & Partner Characteristics
Your Spouse Palace is governed by **${ziweiData.keyHighlights.spousePalace.primaryStar.name}**. In relationships, you seek intellectual resonance, mutual respect, and emotional loyalty above all else. You are drawn to partners who are grounded, supportive, and self-aware.

#### 2.2 Elemental Harmony in Relationships
Since your chart contains strong **${domElem}** and seeks **${lackElem}**, partnering with individuals who possess prominent **${lackElem}** element energy creates natural energetic balance. This combination fosters warm communication and long-term domestic peace.

---

### CHAPTER 3: HEALTH, ELEMENTAL VITALITY & TCM METAPHYSICS

In Traditional Chinese Medicine metaphysics, optimal physical vitality requires harmony among the Five Elements.

#### 3.1 Organ System Focus
Your chart shows **${domElem}** as dominant and **${lackElem}** as lacking. Pay careful attention to organ systems associated with **${lackElem}**:
- *Wood*: Liver, Gallbladder, Nervous System, Eyes
- *Fire*: Heart, Small Intestine, Blood Circulation
- *Earth*: Spleen, Stomach, Digestive Tract
- *Metal*: Lungs, Large Intestine, Respiratory Health
- *Water*: Kidneys, Bladder, Immune Balance

#### 3.2 Wellness & Energy Recommendations
Incorporate daily mindfulness, adequate hydration, outdoor walking in nature, and balanced nutrition to replenish your **${lackElem}** energy. Avoid chronic overworking during seasonal transition periods.

---

### CHAPTER 4: WEALTH CAPACITY, INVESTMENTS & FAMILY HERITAGE

#### 4.1 Wealth Accumulation Pattern
Your Wealth Palace features **${ziweiData.keyHighlights.wealthPalace.primaryStar.name}**, indicating a steady, accumulative wealth creation model. You are built for long-term compound growth rather than speculative gambling.

#### 4.2 Asset Allocation Strategy
- **Recommended**: Index funds, real estate, blue-chip assets, continuous personal skillset investment.
- **Caution**: Avoid high-leverage speculative schemes or unvetted financial ventures.

#### 4.3 Family & Ancestral Dynamics
You play a stabilizing, protective pillar role within your family circle. Relatives often seek your balanced advice during major financial or familial decisions.

---

## SECTION V: 12-MONTH STRATEGIC TRANSIT FORECAST

- **Months 1–3**: Focus on internal consolidation, skill upgrading, and organizing financial assets.
- **Months 4–6**: Favorable window for professional advancement, launching new projects, and expanding network alliances.
- **Months 7–9**: Focus on relationship harmony, family wellness, and elemental health rebalancing.
- **Months 10–12**: Harvesting period for career rewards, long-term asset review, and strategic planning for the year ahead.

---

**END OF REPORT**  
*Document generated by Astraea AI Destiny Intelligence Engine. Copyright Astraea Metaphysics.*
`;

  // Trigger browser file download
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `Astraea_Detailed_Destiny_Report_${dayMaster.name}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
